# Generated by Django 4.1.6 on 2023-03-04 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(
                editable=False, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='team',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(
                editable=False, null=True, unique=True, verbose_name='slug'),
        ),
    ]
