# Generated by Django 4.1.6 on 2023-03-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('team', '0008_alter_player_slug_alter_team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.SlugField(
                blank=True, editable=False, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(
                blank=True, editable=False, unique=True, verbose_name='slug'),
        ),
    ]
