# Generated by Django 4.1.6 on 2023-03-04 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('team', '0009_alter_player_slug_alter_team_slug'),
        ('match', '0018_match_won'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerBallStats',
            new_name='PlayerBallStat',
        ),
        migrations.RenameModel(
            old_name='PlayerBatStats',
            new_name='PlayerBatStat',
        ),
        migrations.RenameModel(
            old_name='TeamStats',
            new_name='TeamStat',
        ),
    ]
