# Generated by Django 4.1.6 on 2023-03-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0002_rename_playerballstats_playerballstat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerballstat',
            name='overs',
            field=models.FloatField(
                blank=True, null=True, verbose_name='overs'),
        ),
    ]
