# Generated by Django 4.1.6 on 2023-03-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ball', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='score',
            field=models.CharField(choices=[('0', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('6', '6')],
                                   default='0', max_length=1, verbose_name='score'),
        ),
    ]
