# Generated by Django 4.1.6 on 2023-03-02 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('team', '0001_initial'),
        ('match', '0002_alter_match_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='round',
            name='name',
        ),
        migrations.AddField(
            model_name='match',
            name='first_balling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='first_balling_set', to='team.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='first_batting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='first_batting_set', to='team.team'),
        ),
        migrations.AddField(
            model_name='round',
            name='balling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='balling_set', to='team.team'),
        ),
        migrations.AddField(
            model_name='round',
            name='batting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='batting_set', to='team.team'),
        ),
    ]
