# Generated by Django 4.1.6 on 2023-03-02 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('team', '0001_initial'),
        ('match', '0004_alter_match_first_balling_alter_match_first_batting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='elected',
            field=models.CharField(choices=[('B', 'Batting'), ('F', 'Balling')], default='F', max_length=1,
                                   verbose_name='elected'),
        ),
        migrations.AddField(
            model_name='match',
            name='toss_win',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='toss_win_set', to='team.team'),
        ),
    ]
