# Generated by Django 4.1.6 on 2023-03-02 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('team', '0001_initial'),
        ('match', '0005_match_elected_match_toss_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='toss_win',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toss_win_set',
                                    to='team.team'),
        ),
    ]
