# Generated by Django 4.1.6 on 2023-03-03 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('match', '0006_alter_match_toss_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='round',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
    ]
