# Generated by Django 4.1.6 on 2023-03-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('match', '0008_match_created_match_modified_round_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='elected',
            field=models.CharField(choices=[('B', 'Bat'), ('F', 'Field')], default='F', max_length=1,
                                   verbose_name='elected'),
        ),
    ]
