# Generated by Django 4.1.6 on 2023-03-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('match', '0009_alter_match_elected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='slug'),
        ),
    ]
