# Generated by Django 4.1.6 on 2023-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('match', '0010_alter_match_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
