# Generated by Django 4.1.6 on 2023-03-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('team', '0002_player_created_player_modified_player_slug_and_more'),
        ('match', '0011_round_name_alter_match_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='first_balling',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='first_balling_set', to='team.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='first_batting',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='first_batting_set', to='team.team'),
        ),
    ]
