# Generated by Django 4.1.6 on 2023-03-04 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('team', '0009_alter_player_slug_alter_team_slug'),
        ('match', '0017_alter_match_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='won',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='won_set', to='team.team'),
        ),
    ]
